"use client";
import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";

export default function InsightsPage() {
  const [data, setData] = useState<any>(null);
  const [activeTab, setActiveTab] = useState<"overview" | "mood" | "insights">("overview");
  const [goalState, setGoalState] = useState<{ completed: number; total: number; tasks: any[] }>({ completed: 0, total: 0, tasks: [] });
  const [togglingGoal, setTogglingGoal] = useState<number | null>(null);
  const router = useRouter();

  useEffect(() => {
    fetch("/api/stats").then(r => r.json()).then(d => {
      setData(d);
      setGoalState(d.goals || { completed: 0, total: 0, tasks: [] });
    }).catch(() => {});
  }, []);

  const handleToggleGoal = useCallback(async (index: number) => {
    setTogglingGoal(index);
    // Optimistic update
    setGoalState(prev => {
      const newTasks = [...prev.tasks];
      newTasks[index] = { ...newTasks[index], done: !newTasks[index].done };
      const completed = newTasks.filter(t => t.done).length;
      return { completed, total: prev.total, tasks: newTasks };
    });
    try {
      const res = await fetch("/api/goals/toggle", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ index }),
      });
      if (res.ok) {
        const result = await res.json();
        setGoalState(result.goals);
      }
    } catch { /* keep optimistic state */ }
    setTogglingGoal(null);
  }, []);

  if (!data) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "#f9f9f9" }}>
        <div style={{ textAlign: "center" }}>
          <span className="material-symbols-outlined text-5xl text-[#3e637f] animate-spin">progress_activity</span>
          <p style={{ marginTop: 12, color: "#5b6061", fontSize: 14 }}>Loading ML insights...</p>
        </div>
      </div>
    );
  }

  const moodChart = data.moodChart || [];
  const goals = goalState;
  const insights = data.ai_insights || [];
  const breakdown = data.breakdown || {};
  const recommendations = data.recommendations || {};
  const mlAvailable = data.ml_available;
  const aiSource = data.ai_source || "none";

  // SVG Chart helpers
  const maxScore = 100;
  const chartWidth = 400;
  const chartHeight = 160;
  const barWidth = chartWidth / Math.max(moodChart.length, 1) - 12;

  return (
    <>
{/* NAV */}
<nav className="fixed top-0 w-full z-50 bg-[#f9f9f9]/80 backdrop-blur-xl">
<div className="flex justify-between items-center px-8 h-20 max-w-7xl mx-auto w-full font-['Manrope']">
<div className="text-2xl font-bold text-[#2f3334]">Serene Sanctuary</div>
<div className="hidden md:flex items-center space-x-12">
<a className="text-[#5b6061] font-medium hover:text-[#3e637f] transition-colors" href="/">Dashboard</a>
<a className="text-[#5b6061] font-medium hover:text-[#3e637f] transition-colors" href="/exercises">Exercises</a>
<a className="text-[#3e637f] font-bold border-b-2 border-[#3e637f] pb-1" href="/insights">Insights</a>
</div>
<a href="/" className="text-[#5b6061] hover:text-[#3e637f] text-sm font-semibold flex items-center gap-2"><span className="material-symbols-outlined">arrow_back</span> Back</a>
</div>
</nav>

<main className="pt-28 pb-12 px-6 lg:px-12 max-w-7xl mx-auto min-h-screen">
<header className="mb-8">
  <div className="flex items-center gap-3 mb-2">
    <h2 className="text-4xl font-extrabold text-[#2f3334] tracking-tight font-['Manrope']">Your Insights</h2>
    {mlAvailable && (
      <span style={{ padding: "4px 12px", borderRadius: 999, background: aiSource === "gemini" ? "linear-gradient(135deg, #4285f4, #34a853)" : "linear-gradient(135deg, #3e637f, #6b9080)", color: "white", fontSize: 11, fontWeight: 700, letterSpacing: 1 }}>{aiSource === "gemini" ? "AI-POWERED ✨" : "ML-POWERED"}</span>
    )}
  </div>
  <p className="text-lg text-[#5b6061] font-medium">
    {mlAvailable ? "Personalized insights generated by AI analyzing your patterns in real-time." : "Insights based on your activity data."}
  </p>
</header>

{/* TABS */}
<div className="flex gap-2 mb-8">
{(["overview", "mood", "insights"] as const).map(tab => (
  <button key={tab} onClick={() => setActiveTab(tab)}
    style={{ padding: "10px 24px", borderRadius: 999, fontWeight: 700, fontSize: 13, cursor: "pointer", border: "none", background: activeTab === tab ? "#3e637f" : "#f2f4f4", color: activeTab === tab ? "white" : "#5b6061", transition: "all 0.3s" }}>
    {tab === "overview" ? "Overview" : tab === "mood" ? "Mood Analytics" : "AI Insights"}
  </button>
))}
</div>

{/* TAB: OVERVIEW */}
{activeTab === "overview" && (
<div className="grid grid-cols-1 md:grid-cols-12 gap-8">
{/* Score Cards */}
<div className="md:col-span-4 bg-gradient-to-br from-[#3e637f] to-[#2a4a5c] rounded-xl p-8 text-white">
  <p className="text-xs uppercase tracking-widest opacity-70 mb-2">Wellness Score</p>
  <div className="flex items-end gap-2">
    <span style={{ fontSize: 56, fontWeight: 900, lineHeight: 1 }}>{data.wellness_score || Math.round((data.mindfulnessMinutes?.goalPercent || 75))}</span>
    <span style={{ fontSize: 16, opacity: 0.6, marginBottom: 8 }}>/100</span>
  </div>
  <p className="text-sm opacity-70 mt-2">
    {data.burnout_risk === "low" ? "Low burnout risk — keep it up!" : data.burnout_risk === "moderate" ? "Moderate stress — consider extra self-care" : data.burnout_risk || "Based on your mood + activity patterns"}
  </p>
</div>

<div className="md:col-span-4 bg-white rounded-xl p-8 border border-[#e5e7e8]">
  <p className="text-xs uppercase tracking-widest text-[#5b6061] mb-2">Resilience Score</p>
  <div className="flex items-end gap-2">
    <span style={{ fontSize: 56, fontWeight: 900, color: "#6b9080", lineHeight: 1 }}>{data.resilience?.score || 8.4}</span>
    <span style={{ fontSize: 16, color: "#5b6061", marginBottom: 8 }}>/10</span>
  </div>
  <p className="text-sm text-[#5b6061] mt-2">Top {data.resilience?.percentile || 92}% of users</p>
</div>

<div className="md:col-span-4 bg-white rounded-xl p-8 border border-[#e5e7e8]">
  <p className="text-xs uppercase tracking-widest text-[#5b6061] mb-2">Stress Index</p>
  <div className="flex items-end gap-2">
    <span style={{ fontSize: 56, fontWeight: 900, color: (data.stress_index || 25) > 50 ? "#ef4444" : "#3e637f", lineHeight: 1 }}>{data.stress_index || 25}</span>
    <span style={{ fontSize: 16, color: "#5b6061", marginBottom: 8 }}>/100</span>
  </div>
  <p className="text-sm text-[#5b6061] mt-2">{(data.stress_index || 25) < 30 ? "Excellent — very low stress" : (data.stress_index || 25) < 50 ? "Moderate — room for improvement" : "Elevated — prioritize rest"}</p>
</div>

{/* Wellness Breakdown */}
{breakdown && Object.keys(breakdown).length > 0 && (
<div className="md:col-span-6 bg-white rounded-xl p-8 border border-[#e5e7e8]">
  <h3 className="text-lg font-bold text-[#2f3334] mb-6 flex items-center gap-2">
    <span className="material-symbols-outlined text-[#3e637f]">analytics</span> Wellness Breakdown
    {mlAvailable && <span style={{ fontSize: 10, padding: "2px 8px", borderRadius: 999, background: "#d6e8f5", color: "#3e637f", fontWeight: 700 }}>ML</span>}
  </h3>
  <div className="space-y-4">
    {[
      { key: "mood_stability", label: "Mood Stability", icon: "mood" },
      { key: "sleep_quality", label: "Sleep Quality", icon: "bedtime" },
      { key: "activity_level", label: "Activity Level", icon: "fitness_center" },
      { key: "consistency", label: "Consistency", icon: "trending_up" },
    ].map(item => {
      const value = breakdown[item.key] || 0;
      return (
        <div key={item.key}>
          <div className="flex justify-between mb-1">
            <span className="text-sm font-medium text-[#5b6061] flex items-center gap-2">
              <span className="material-symbols-outlined text-base text-[#3e637f]">{item.icon}</span>{item.label}
            </span>
            <span className="text-sm font-bold text-[#2f3334]">{Math.round(value)}%</span>
          </div>
          <div className="w-full bg-[#e5e7e8] h-2 rounded-full overflow-hidden">
            <div className="h-full rounded-full transition-all duration-1000" style={{ width: Math.round(value) + "%", background: value > 70 ? "#6b9080" : value > 40 ? "#3e637f" : "#ef4444" }}></div>
          </div>
        </div>
      );
    })}
  </div>
</div>
)}

{/* Goals */}
<div className="md:col-span-6 bg-white rounded-xl p-8 border border-[#e5e7e8]">
  <h3 className="text-lg font-bold text-[#2f3334] mb-4 flex items-center gap-2">
    <span className="material-symbols-outlined text-[#3e637f]">task_alt</span> Weekly Goals
  </h3>
  <div className="mb-4">
    <div className="flex justify-between mb-2">
      <span className="text-sm text-[#5b6061]">Completed</span>
      <span className="text-sm font-bold text-[#3e637f]">{goals.completed}/{goals.total}</span>
    </div>
    <div className="w-full bg-[#e5e7e8] h-3 rounded-full overflow-hidden">
      <div className="h-full rounded-full bg-[#6b9080] transition-all duration-1000" style={{ width: (goals.total > 0 ? Math.round(goals.completed / goals.total * 100) : 0) + "%" }}></div>
    </div>
  </div>
  <div className="space-y-2 max-h-64 overflow-y-auto">
    {goals.tasks?.map((task: any, i: number) => (
      <button key={i} type="button" onClick={() => handleToggleGoal(i)} disabled={togglingGoal === i}
        className="w-full flex items-center gap-3 py-3 px-2 border-b border-[#f2f4f4] last:border-0 rounded-lg hover:bg-[#f8f9fa] transition-all cursor-pointer text-left disabled:opacity-50"
        style={{ background: task.done ? "rgba(107,144,128,0.06)" : "transparent" }}>
        {togglingGoal === i ? (
          <span className="material-symbols-outlined text-lg text-[#3e637f] animate-spin">progress_activity</span>
        ) : (
          <span className="material-symbols-outlined text-lg" style={{ color: task.done ? "#6b9080" : "#ccc" }}>{task.done ? "check_circle" : "radio_button_unchecked"}</span>
        )}
        <span className="text-sm flex-1" style={{ color: task.done ? "#5b6061" : "#2f3334", textDecoration: task.done ? "line-through" : "none", transition: "all 0.3s" }}>{task.name}</span>
        {task.done && <span style={{ fontSize: 10, padding: "2px 8px", borderRadius: 999, background: "#d4edda", color: "#155724", fontWeight: 700 }}>DONE</span>}
      </button>
    ))}
  </div>
</div>

{/* Badges */}
<div className="md:col-span-12">
  <div className="flex flex-wrap gap-3">
    {(data.badges || []).map((badge: any, i: number) => (
      <div key={i} className="bg-[#f2f4f4] px-5 py-3 rounded-full flex items-center gap-2">
        <span className="material-symbols-outlined text-[#3e637f] text-lg">{badge.icon}</span>
        <span className="text-sm font-bold text-[#2f3334]">{badge.label}</span>
      </div>
    ))}
  </div>
</div>
</div>
)}

{/* TAB: MOOD ANALYTICS */}
{activeTab === "mood" && (
<div className="grid grid-cols-1 md:grid-cols-12 gap-8">
{/* Mood Chart */}
<div className="md:col-span-8 bg-white rounded-xl p-8 border border-[#e5e7e8]">
  <h3 className="text-lg font-bold text-[#2f3334] mb-6">Mood Vitality — Last 7 Days</h3>
  <svg width="100%" viewBox={`0 0 ${chartWidth} ${chartHeight + 40}`} className="overflow-visible">
    {/* Grid lines */}
    {[0, 25, 50, 75, 100].map(v => (
      <g key={v}>
        <line x1="0" y1={chartHeight - (v / maxScore) * chartHeight} x2={chartWidth} y2={chartHeight - (v / maxScore) * chartHeight} stroke="#f0f0f0" strokeWidth="1" />
        <text x="-5" y={chartHeight - (v / maxScore) * chartHeight + 4} fontSize="10" fill="#aaa" textAnchor="end">{v}</text>
      </g>
    ))}
    {/* Bars */}
    {moodChart.map((d: any, i: number) => {
      const barH = (d.score / maxScore) * chartHeight;
      const x = i * (chartWidth / moodChart.length) + 6;
      const color = d.score > 70 ? "#6b9080" : d.score > 40 ? "#3e637f" : "#c97a5a";
      return (
        <g key={i}>
          <rect x={x} y={chartHeight - barH} width={barWidth} height={barH} rx={6} fill={color} opacity={d.hasMood ? 1 : 0.3}>
            <title>{d.day}: {d.score}</title>
          </rect>
          <text x={x + barWidth / 2} y={chartHeight + 16} textAnchor="middle" fontSize="11" fill="#5b6061" fontWeight="600">{d.day}</text>
          {d.hasMood && <text x={x + barWidth / 2} y={chartHeight - barH - 6} textAnchor="middle" fontSize="10" fill={color} fontWeight="700">{d.score}</text>}
        </g>
      );
    })}
  </svg>
</div>

{/* Overview Stats */}
<div className="md:col-span-4 space-y-4">
  <div className="bg-white rounded-xl p-6 border border-[#e5e7e8]">
    <p className="text-xs text-[#5b6061] uppercase tracking-widest mb-1">Total Sessions</p>
    <p className="text-3xl font-black text-[#2f3334]">{data.overview?.totalSessions || 0}</p>
  </div>
  <div className="bg-white rounded-xl p-6 border border-[#e5e7e8]">
    <p className="text-xs text-[#5b6061] uppercase tracking-widest mb-1">Total Minutes</p>
    <p className="text-3xl font-black text-[#3e637f]">{data.overview?.totalMinutes || 0}</p>
  </div>
  <div className="bg-white rounded-xl p-6 border border-[#e5e7e8]">
    <p className="text-xs text-[#5b6061] uppercase tracking-widest mb-1">Current Streak</p>
    <p className="text-3xl font-black text-[#6b9080]">{data.overview?.currentStreak || 0} days</p>
  </div>
</div>

{/* Mood Score (AI Insight) */}
<div className="md:col-span-12 bg-gradient-to-r from-[#3e637f] to-[#6b9080] rounded-xl p-8 text-white">
  <div className="flex items-start gap-3">
    <span className="material-symbols-outlined text-3xl opacity-80">psychology</span>
    <div>
      <p className="text-sm font-bold uppercase tracking-widest opacity-70 mb-2">AI Analysis</p>
      <p className="text-lg leading-relaxed">{data.aiInsight || "Start tracking your mood daily to unlock personalized AI insights."}</p>
    </div>
  </div>
</div>
</div>
)}

{/* TAB: AI INSIGHTS */}
{activeTab === "insights" && (
<div className="grid grid-cols-1 md:grid-cols-12 gap-8">
{/* ML Insights */}
<div className="md:col-span-8 space-y-4">
  <h3 className="text-lg font-bold text-[#2f3334] mb-2 flex items-center gap-2">
    <span className="material-symbols-outlined text-[#3e637f]">auto_awesome</span>
    Machine Learning Insights
    {mlAvailable && <span style={{ fontSize: 10, padding: "2px 8px", borderRadius: 999, background: "#6b9080", color: "white", fontWeight: 700 }}>LIVE</span>}
  </h3>

  {insights.length > 0 ? insights.map((insight: any, i: number) => (
    <div key={i} className="bg-white rounded-xl p-6 border border-[#e5e7e8] hover:shadow-md transition-shadow">
      <div className="flex items-start gap-4">
        <div style={{ width: 40, height: 40, borderRadius: 12, display: "flex", alignItems: "center", justifyContent: "center",
          background: insight.priority === "high" ? "#fef3c7" : "#d6e8f5",
          color: insight.priority === "high" ? "#d97706" : "#3e637f" }}>
          <span className="material-symbols-outlined">
            {insight.type === "warning" ? "warning" : insight.type === "meditation_helps" ? "self_improvement" : insight.type === "sleep_correlation" ? "bedtime" : insight.type === "streak_momentum" ? "local_fire_department" : "insights"}
          </span>
        </div>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-bold uppercase tracking-widest text-[#3e637f]">{insight.type?.replace(/_/g, " ")}</span>
            <span style={{ fontSize: 9, padding: "2px 6px", borderRadius: 999, background: insight.priority === "high" ? "#fef3c7" : "#f2f4f4", color: insight.priority === "high" ? "#d97706" : "#5b6061", fontWeight: 700 }}>{insight.priority}</span>
          </div>
          <p className="text-sm text-[#2f3334] leading-relaxed">{insight.text}</p>
        </div>
      </div>
    </div>
  )) : (
    <div className="bg-white rounded-xl p-8 text-center border border-[#e5e7e8]">
      <span className="material-symbols-outlined text-4xl text-[#3e637f] mb-2">psychology</span>
      <p className="text-[#5b6061] font-medium">
        Not enough data yet. Keep logging moods and sessions to unlock AI-powered insights.
      </p>
    </div>
  )}
</div>

{/* Recommendations */}
<div className="md:col-span-4 space-y-4">
  <h3 className="text-lg font-bold text-[#2f3334] mb-2 flex items-center gap-2">
    <span className="material-symbols-outlined text-[#6b9080]">recommend</span> For You
  </h3>

  {recommendations?.primary_recommendation && (
    <div className="bg-gradient-to-br from-[#6b9080] to-[#4a7c6f] rounded-xl p-6 text-white">
      <p className="text-xs uppercase tracking-widest opacity-70 mb-1">Top Pick</p>
      <p className="font-bold text-lg mb-1">{recommendations.primary_recommendation.title}</p>
      <p className="text-sm opacity-80 mb-3">{recommendations.primary_recommendation.duration_minutes} min • {recommendations.primary_recommendation.type}</p>
      <p className="text-xs opacity-60">{recommendations.primary_recommendation.reason}</p>
      <button onClick={() => router.push("/exercises")} className="mt-4 bg-white text-[#2d5a4e] px-5 py-2 rounded-full text-sm font-bold hover:scale-105 transition-transform">Start Now</button>
    </div>
  )}

  {recommendations?.alternatives?.map((alt: any, i: number) => (
    <button key={i} onClick={() => router.push("/exercises")}
      className="w-full bg-white rounded-xl p-4 border border-[#e5e7e8] flex items-center gap-3 hover:shadow-md transition-all text-left">
      <div className="bg-[#d6e8f5] p-2 rounded-lg">
        <span className="material-symbols-outlined text-[#3e637f]">{alt.type === "Breathing" ? "air" : alt.type === "Sleep" ? "bedtime" : "self_improvement"}</span>
      </div>
      <div>
        <p className="text-sm font-bold text-[#2f3334]">{alt.title}</p>
        <p className="text-xs text-[#5b6061]">{alt.duration_minutes} min</p>
      </div>
    </button>
  ))}

  {recommendations?.reasoning && recommendations.reasoning.length > 0 && (
    <div className="bg-[#f2f4f4] rounded-xl p-4">
      <p className="text-xs font-bold text-[#5b6061] uppercase tracking-widest mb-2">Why these?</p>
      {recommendations.reasoning.map((r: string, i: number) => (
        <p key={i} className="text-xs text-[#5b6061] mb-1">• {r}</p>
      ))}
    </div>
  )}
</div>
</div>
)}
</main>

{/* MOBILE NAV */}
<nav className="md:hidden fixed bottom-0 left-0 right-0 h-20 bg-white/90 backdrop-blur-lg border-t border-[#e5e7e8] z-50 px-6 flex justify-between items-center">
<button type="button" onClick={() => router.push("/")} className="flex flex-col items-center space-y-1 text-[#5b6061]">
<span className="material-symbols-outlined">dashboard</span><span className="text-[10px] font-bold">Home</span>
</button>
<button type="button" onClick={() => router.push("/companion")} className="flex flex-col items-center space-y-1 text-[#5b6061]">
<span className="material-symbols-outlined">psychology</span><span className="text-[10px] font-bold">Guide</span>
</button>
<button type="button" onClick={() => router.push("/exercises")} className="relative -top-6 bg-[#3e637f] text-white w-14 h-14 rounded-full shadow-lg flex items-center justify-center">
<span className="material-symbols-outlined text-3xl">add</span>
</button>
<button type="button" onClick={() => router.push("/exercises")} className="flex flex-col items-center space-y-1 text-[#5b6061]">
<span className="material-symbols-outlined">spa</span><span className="text-[10px] font-bold">Relax</span>
</button>
<button type="button" onClick={() => router.push("/insights")} className="flex flex-col items-center space-y-1 text-[#3e637f]">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 1" }}>auto_graph</span><span className="text-[10px] font-bold">Stats</span>
</button>
</nav>
    </>
  );
}